### PR TITLE
daniel413x/supplement tax calculator service tests

### PR DESCRIPTION
**Pull request by daniel413x**

### CODE REVIEW

**Review by brittshook — CHANGES_REQUESTED** [review]
Add method to teardown mocks (see comments on other PRs)

**Review by rey1776 — APPROVED** [review]
Looks good to me and the comments are helpful.

**Comment by brittshook** [comment]
@daniel413x can you come in a resolve conflicts please

**Comment by brittshook** [comment]
Re: fix merge conflicts

**Review by brittshook — APPROVED** [review]
Good work!

**Pull request merged**
